# 这些是支持者链接。取消注释并填写你想要显示的链接。
# 更多信息：https://docs.github.com/en/github/administering-a-repository/managing-repository-settings/configuring-the-sponsor-button

# github: # 用你的 GitHub 用户名替换
# patreon: # 用你的 Patreon 用户名替换
# open_collective: # 用你的 Open Collective 用户名替换
# ko_fi: # 用你的 Ko-fi 用户名替换
# tidelift: # 用你的 Tidelift 平台名称替换
# community_bridge: # 用你的 Community Bridge 项目名称替换
# liberapay: # 用你的 Liberapay 用户名替换
# issuehunt: # 用你的 IssueHunt 用户名替换
# otechie: # 用你的 Otechie 用户名替换
# lfx_crowdfunding: # 用你的 LFX Crowdfunding 项目名称替换
# custom: # 用你的自定义 URL 替换

